# Generated by Django 4.2.4 on 2023-09-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2_app', '0004_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'registration_date'], 'verbose_name': 'Клиентов', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Сделки', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
    ]
